-- After a Dev DB wipe, recreate ONLY our lead-distribution objects.
-- Prisma/CRM tables (companies, pools, profiles, contracts, …) come from
-- the boss / app migrate first. Then run these files IN ORDER in Supabase:
--
--   0) Boss Prisma migrate, then 06_crm_pool_rule_uuid.sql (existing DBs with ld_rule_* ids)
--   1) 04_seed_ld_pools.sql             core pools (UUID id, code key) + tag rules
--   2) 09_sync_provider_pools.sql       OPTIONAL — parked until supplier/campaign on
--   2b) 10_park_supplier_routing.sql   deactivate supplier rules + provider family
--   2c) 11_reclaim_from_parked_pools.sql  move past-sale cos out of supplier/Unassigned
--   2d) 12_hide_parked_pools_from_agents.sql  drop supplier/Unassigned/Upselling from Pool filter
--       Fix PRIVATE one-owner links: 12a_fix_private_one_owner.sql
--       Undo supplier links: 12_revert_hide_parked_pools.sql
--   Turn supplier back on: see 13_turn_on_supplier_routing.md
--   4) 02_split_schema.sql              policy / member / filter (unused while
--      apply stops at STANDARD shared pools)
--   5) apply_ld_apply_batch.sql         ld_apply_batch + ld_apply_batch_run()
--   6) 24_janitor.sql                   ld_janitor_run()
--   7) 25_cron.sql                      docs only — cron is the Databricks Job
--   8) 16 + last-sale fill              ONLY if sourcebridge exists (migrate)
--
-- Do NOT run 18/19/21 (profile/agent share). Allocate to PRIVATE agent pools
-- waits until we wire pool_links + pool_profiles.
-- Do NOT run 03 Tom/Dick/Harry or 20 unless you need that cleanup.
--
-- App tables we write into (Prisma-owned):
--   pools                       type STANDARD = shared parent, PRIVATE = agent
--   pool_links                  parent STANDARD → child PRIVATE (later)
--   pool_profiles               who can work a pool (later)
--   companies.poolId            current pool
--   company_pool_placements     open/closed history of a company in a pool
--   company_pool_audits         who moved the company
--
-- Tables / functions this script family owns:
--   crm_provider_family
--   crm_provider_family_pattern
--   crm_pool_rule
--   crm_pool_split_policy
--   crm_pool_split_filter
--   crm_pool_member
--   crm_company_load_sale          (optional fallback)
--   ld_apply_batch
--   ld_apply_batch_run()
--   ld_janitor_run()
-- Shared pool codes in pools: EON, EON_DFV, BG, UB, OTHER, UNASSIGNED,
--   COMPLAINT, RETENTION, PAST_RETENTION, UPSELLING, CUSTOMER_CARE, CORPORATE
--   (+ per-supplier codes from 09). pools.id = UUID v4.

-- Guides:
--   PARKED_STATE.md              — current parked nightly
--   RELEASE_MIGRATION.md         — release: 16 fallback + functions + park
--   NEW_SUPPLIER_AND_TURN_ON.md  — new provider + supplier turn-on

SELECT 'See PARKED_STATE.md, RELEASE_MIGRATION.md, NEW_SUPPLIER_AND_TURN_ON.md' AS rebuild_order;
